version: '3'

services:
  postgresql:
    image: postgres:14.6-alpine
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-1}
      POSTGRES_DB: ${POSTGRESQL_DATABASE_NAME:-currency_microservice}
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
#    volumes:
#      - ./docker-volumes/elastic-data:/usr/share/elasticsearch/data
  logstash:
    image: logstash:7.17.9
    container_name: logstash
    restart: always
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/:ro
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.17.9
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    volumes:
      - "../../docker-volumes/jenkins:/var/jenkins_home"
#      - ".:/var/currency-microservices:ro"
#    environment:
#      JAVA_OPTS: -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
  sonarqube:
    image: sonarqube:9-community
    container_name: sonarqube
    ports:
      - "9900:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    depends_on:
      - jenkins
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - elasticsearch
  config-server:
    build: ./config-server
    container_name: config-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      AUTH_SERVER_URL: http://auth-server:9000
      ACCESS_TOKEN_TTL_MS: 1000 * 60 * 30
    ports:
      - "8888:8888"
    depends_on:
      - elasticsearch
      - eureka-server
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8765:8765"
    depends_on:
      - elasticsearch
      - eureka-server
      - config-server
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  auth-server:
    build: ./auth-server
    container_name: auth-server
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
      - eureka-server
      - config-server
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  currency-rate:
    build: ./currency-rate
    container_name: currency-rate
    depends_on:
      - elasticsearch
      - eureka-server
      - config-server
      - gateway
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
  account-processor:
    build: ./account-processor
    container_name: account-processor
    depends_on:
      - elasticsearch
      - eureka-server
      - config-server
      - gateway
      - rabbitmq
      - postgresql
      - currency-rate
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:-1}
      POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME:-currency_microservice}
      RABBITMQ_HOST: rabbitmq
  account-history:
    build: ./account-history
    container_name: account-history
    depends_on:
      - elasticsearch
      - eureka-server
      - config-server
      - gateway
      - rabbitmq
      - postgresql
      - account-processor
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka
      POSTGRESQL_HOST: postgresql
      POSTGRESQL_PORT: 5432
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD:-1}
      POSTGRESQL_DATABASE_NAME: ${POSTGRESQL_DATABASE_NAME:-currency_microservice}
      RABBITMQ_HOST: rabbitmq