spring:
  application:
    name: auth-server

logging:
  level:
    org:
      springframework:
        security: TRACE

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 9000

app:
  issuer-url: ${ISSUER_URL:http://auth-server:${server.port}}
