logging:
  level:
    org:
      springframework:
        security: TRACE

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 9000

app:
  issuer-uri: ${ISSUER_URI:http://auth-server:${server.port}}
  # по умол. 1 час
  access-token-ttl-ms: "#{${ACCESS_TOKEN_TTL_MS:1000 * 60 * 60}}"
