logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 9000

app:
  issuer-uri: ${AUTH_SERVER_URL:http://auth-server:${server.port}}
  # по умол. 1 час
  access-token-ttl-ms: "#{${ACCESS_TOKEN_TTL_MS:1000 * 60 * 60}}"
