spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
#        httpclient:
#          wiretap: true
#        httpserver:
#          wiretap: true

logging:
  level:
    reactor:
      netty: debug
    org:
      springframework:
        cloud:
          gateway: debug

server:
  port: 8765
