
cloud:
  gateway:
    discovery:
      locator:
        lower-case-service-id: true
        enabled: true
#      httpclient:
#        wiretap: true
#      httpserver:
#        wiretap: true

logging:
  level:
    reactor:
      netty: debug
    org:
      springframework:
        cloud:
          gateway: debug

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}

server:
  port: 8765
